diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: "left_wheel"
  right_wheel: "right_wheel"
  wheel_separation: 0.6      # 你小车两轮的距离
  wheel_radius: 0.2           # 轮半径
  cmd_vel_timeout: 0.5
  publish_rate: 50
  linear:
    x:
      gain: 1.0
      has_velocity_limits: false
  angular:
    z:
      gain: 1.0
      has_velocity_limits: false
